#!/bin/bash
sed --in-place "s|access_key|access_key = $AWS_ACCESS_KEY|" .s3cfg
sed --in-place "s|secret_key|secret_key = $AWS_SECRET_KEY|" .s3cfg
mkdir -p ~/.ssh
s3cmd -c .s3cfg get s3://progrium-private/test.pem ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa