#!/bin/bash
set -ex;

REMOTE=$1
REPO=$2

# get current DATABASE_URL
DATABASE_URL=$(ssh $REMOTE config:get $REPO DATABASE_URL || true)
echo $DATABASE_URL
[[ "$DATABASE_URL" == "" ]]

# try link to non-existing database
ssh $REMOTE mariadb:link $REPO $REPO-test-db || true

# create and destroy
ssh $REMOTE mariadb:create $REPO-test-db
ssh $REMOTE mariadb:destroy $REPO-test-db

# create and link database
ssh $REMOTE mariadb:create $REPO-test-db
ssh $REMOTE mariadb:link $REPO $REPO-test-db
TEST_DB_URL=$(ssh $REMOTE config:get $REPO DATABASE_URL)
echo $TEST_DB_URL
[[ "$TEST_DB_URL" != "" ]]
