#!/bin/bash

source "$(dirname $0)/../dokku_common"

case "$1" in
  tag:add)
    verify_app_name "$2"
    verify_max_args 3 "$@"
    print_acl_access "developer" "$2"
    ;;

  tag:rm)
    verify_app_name "$2"
    verify_max_args 3 "$@"
    print_acl_access "developer" "$2"
    ;;

  tag:list)
    verify_app_name "$2"
    print_acl_access "developer" "$2"
    ;;
esac
