#!/bin/bash

REMOTE=$1
REPO=$2

custom_check_deploy() {
	output="$(curl --verbose --fail -x "$PROXY_URL" $URL)";
	echo $output;
	test "$output" == "$1"
}

set -xe

custom_check_deploy volumes-test

echo Creating dynamic volumes...
dokku volume:create $2 /usr/share/nginx/html
dokku volume:link $2 $2
dokku volume:info $2
dokku volume:list:apps $2

echo Checking if persistent volume works
dokku exec $2 bash -c "echo persistent-volume > /usr/share/nginx/html/index.html"
custom_check_deploy persistent-volume
dokku exec $2 bash -c "echo persistent-volume-2 > /usr/share/nginx/html/index.html"
custom_check_deploy persistent-volume-2

echo Rebuilding app and checking if volume works
dokku rebuild $2
custom_check_deploy persistent-volume-2

echo Unlinking volume...
dokku volume:unlink $2 $2
custom_check_deploy volumes-test

echo Relinking volume...
dokku volume:link $2 $2
custom_check_deploy persistent-volume-2

echo Creating volume once again...
! dokku volume:create $2 /usr/share/nginx/html

echo Destroying volume...
dokku volume:destroy $2

echo Rebuild app, because its still linked to volume...
dokku rebuild $2

