#!/bin/bash
set -e
NAME="$1"
ID=$(cat | docker run -i -a stdin progrium/buildstep /bin/bash -c "mkdir -p /app && tar -xC /app")
docker commit $ID $NAME > /dev/null
ID=$(docker run -d $NAME /build/builder)
docker attach $ID
docker commit $ID $NAME > /dev/null
