#!/bin/bash

set -e

# create staging area for build layer
layer_stage=`mktemp -d /tmp/buildstep.stage.XXXX`
trap "rm -rf $layer_stage" EXIT

# install buildpacks
buildpacks_dir="$layer_stage/buildpacks"
mkdir $buildpacks_dir
cp -r buildpacks/* $buildpacks_dir

# build directory with build script and app src
build_dir="$layer_stage/build"
mkdir $build_dir
cp $1 $build_dir
cat | tar -x -C $build_dir

# create the layer
build_layer=`mktemp /tmp/buildstep.layer.XXXX`
cd $layer_stage
tar -zcf $build_layer .
mv $build_layer "$build_layer.tgz"
build_layer="$build_layer.tgz"
#trap "rm -rf $build_layer" EXIT

# run the build!
docker run \
  -L layer://base \
  -L "file://$build_layer" \
  --export -- /build/builder
