#!/bin/bash
set -e

[[ $PLUGIN_PATH ]] || { echo "[ERROR] Unable to locate plugins: set \$PLUGIN_PATH"; exit 1; }

if [[ ! -t "0" ]]; then
  input=$(cat)
fi

output_file=$(mktemp /tmp/output.XXXX)
trap "rm $output_file" EXIT

shopt -s nullglob
for plugin in $PLUGIN_PATH/*
do
  [[ -x "$plugin" ]] && (echo "$input" | $plugin "$@" > $output_file) && input=$(cat $output_file)
done
shopt -u nullglob

echo "$input"