#!/bin/bash

APP="$1"

#Old way of storing passwords
if [[ -f "$DOKKU_ROOT/.mongodb/pass_${APP}" ]]; then
  dokku mongodb:link $APP
fi


#new way supports multi db per db
for f in `ls $DOKKU_ROOT/.mongodb/pass_${APP}_*`; do
  DATABASE=$( echo "$f" | cut -d'_' -f3 )
  dokku mongodb:link $APP $DATABASE
done