#!/bin/bash
set -e
echo "----> Building $1 ..."
cd /home/git/buildstep
ID=$(cat | docker run -i -a stdin progrium/buildstep /buildpacks/builder)
docker attach $ID &
docker wait $ID
docker kill $ID
docker commit $ID $1
echo "----> Build complete!"
exit 1 #debug
