#!/bin/bash
set -e
echo "----> Building $1 ..."
APP="app/$1"
ID=$(cat | docker run -i -a stdin progrium/buildstep /bin/bash -c "mkdir -p /app && tar -xC /app")
docker commit $ID $APP > /dev/null
ID=$(docker run -d $APP /buildpacks/builder)
docker attach $ID
docker commit $ID $APP > /dev/null
echo "----> Build complete!"
echo "----> Deploying $1 ..."
ID=$(docker run -d -p 5000 -e PORT=5000 $APP /bin/bash -c "cd /app && ./start")
echo $ID > "$1/CONTAINER"
PORT=$(docker inspect $ID | ruby -e 'require"json";puts JSON.parse(STDIN.read)["NetworkSettings"]["PortMapping"]["5000"]')
echo $PORT > "$1/PORT"
echo
echo "----> Application deployed:"
echo "      http://$(hostname -i | cut -d' ' -f3):$PORT"
exit 1 #debug
