#!/bin/bash
set -e

SELF=`which $0`
HOME_DIR=${HOME_DIR:-"/home"}

case "$1" in
  create) # sshcommand create <user> <command>
    USER="$2"; COMMAND="$3"
    USERHOME="$HOME_DIR/$USER"
    useradd -d $USERHOME $USER || true
    mkdir -p "$USERHOME/.ssh"
    touch $USERHOME/.ssh/authorized_keys
    echo "$COMMAND" > "$USERHOME/.sshcommand"
    chown -R $USER $USERHOME
    ;;

  acl-add) # sshcommand acl-add <user> <name>
    USER="$2"; NAME="$3"
    KEY=$(cat)
    FINGERPRINT=$(ssh-keygen -lf /dev/stdin <<< $(echo $KEY) | awk '{print $2}')
    KEY_PREFIX="command=\"FINGERPRINT=$FINGERPRINT NAME=$NAME \$(<$HOME_DIR/$USER/.sshcommand) \$SSH_ORIGINAL_COMMAND\",no-agent-forwarding,no-user-rc,no-X11-forwarding,no-port-forwarding"
    echo "$KEY_PREFIX $KEY" >> "$HOME_DIR/$USER/.ssh/authorized_keys"
    echo $FINGERPRINT
    ;;

  acl-remove) # sshcommand acl-remove <user> <name>
    USER="$2"; NAME="$3"
    sed --in-place "/ NAME=$NAME /d" "$HOME_DIR/$USER/.ssh/authorized_keys"
    ;;

  *)
    echo "Usage: sshcommand <command> <args...>"
    ;;
esac