#!/bin/bash

source "$(dirname $0)/vars"

cat

[[ -z "$NAME" ]] && [[ $(id -un) != "root" ]] && fail "Access denied. No user supplied."

# http://unix.stackexchange.com/a/67900
if [ "$NAME" != "developer" ] && [ "$NAME" != "deploy" ]; then
    # Allow everything
    exit 0
fi

[[ -z "$FINGERPRINT" ]] && fail "Access denied. No fingerprint supplied."

case "$1" in
    git-hook)
        APP="$2"
        ;;

    git-*)
        APP="$(echo "$2" | perl -pe 's/(?<!\\)'\''//g' | sed 's/\\'\''/'\''/g')"
        ;;

    *)
        if [[ "$NAME" == "developer" ]]; then
          APP="$2"
        else
          fail "Access denied. Please login as an admin."
        fi
        ;;
esac

check_app_name "$APP"

if ! is_fingerprint_allowed "$FINGERPRINT" "$NAME"
then
    fail "Access denied. You don't have permission to access this app."
fi
