#!/bin/bash

source "$(dirname $0)/vars"

cat

[[ -z "$NAME" ]] && [[ $(id -un) != "root" ]] && [[ $(id -un) != "dokku" ]] && fail "Access denied. No user supplied."

# http://unix.stackexchange.com/a/67900
if [[ "$NAME" != "developer" ]] && [[ "$NAME" != "deploy" ]]; then
    # Allow everything
    exit 0
fi

[[ -z "$FINGERPRINT" ]] && fail "Access denied. No fingerprint supplied."

readarray -t LINES < <(: | pluginhook get-acl "$@")
ACL_LEVEL=${LINES[0]}
ACL_APPNAME=${LINES[1]}

if [[ -z "$ACL_LEVEL" ]] || [[ -z "$ACL_APPNAME" ]]; then
    fail "Access denied. You don't have permission to access this command."
fi

check_app_name "$ACL_APPNAME"

case "$ACL_LEVEL" in
    developer)
        if [[ "$NAME" == "developer" ]]; then
            if is_fingerprint_allowed "$FINGERPRINT" "developer"; then
                exit 0
            fi
        fi
        ;;

    deploy)
        if [[ "$NAME" == "developer" ]] || [[ "$NAME" == "deploy" ]]; then
            if is_fingerprint_allowed "$FINGERPRINT" "developer"; then
                exit 0
            fi
            if is_fingerprint_allowed "$FINGERPRINT" "deploy"; then
                exit 0
            fi
        fi
        ;;
esac

fail "Access denied. You don't have permission to access this app."
