#!/bin/bash

source "$(dirname $0)/vars"

case "$1" in
  ssl:generate)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_acl_access "developer" "$2"
    ;;

  ssl:certificate)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_acl_access "developer" "$2"
    ;;

  ssl:key)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_acl_access "developer" "$2"
    ;;

  ssl:selfsigned)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_acl_access "developer" "$2"
    ;;

  ssl:info)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_acl_access "developer" "$2"
    ;;

  ssl:forget)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_acl_access "developer" "$2"
    ;;
esac
