#!/bin/bash
echo "Building..."
ID_FILE=$(mktemp)
vendor/docker-build < Dockerfile | while read line; do 
  [[ $last ]] && echo $last
  echo "$line" > $ID_FILE
  last=$line
done
ID=$(<"$ID_FILE")
rm $ID_FILE
docker tag $ID progrium/buildstep
echo
echo "Saved as progrium/buildstep"