#!/bin/bash
echo "Building container..."
ID_FILE=$(mktemp)
python -u vendor/docker-build < Dockerfile | while read line; do 
  [[ $last ]] && echo $last
  echo "$line" > $ID_FILE
  last=$line
done
ID=$(<"$ID_FILE")
rm $ID_FILE
docker tag $ID progrium/buildstep
echo
echo "Saved container as progrium/buildstep"