#!/usr/bin/env bash

source "$(dirname $0)/vars"

case "$1" in
  domains:get)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    hostnames_for_app "$APP"
	echo "${hostnames[@]}"
	;;

  domains:set)
    verify_app_name "$2"
    shift 2
    echo "$@" > "$DOKKU_ROOT/$APP/HOSTNAME"
    redeploy_app "$APP"
    ;;

  help)
    cat && cat <<EOF
    domains:get <app>                 Get domains for an app
    domains:set <app> <domains...>    Set app domains
EOF
    ;;
esac
