#!/bin/bash

# we don't need that, because we use Ubuntu 14.04LTS
exit 0

# latest stable NGINX 1.4.x with websocket support
apt-get install -qq -y software-properties-common python-software-properties
add-apt-repository -y ppa:nginx/stable
apt-get update
apt-get install -qq -y nginx dnsutils
