#!/bin/bash

cat <<EOF
upstream $APP { server $APP_ADDRESS; }

server {
  listen      [::]:80;
  listen      80;
  server_name ${hostnames[@]} ${redirect_hostnames[@]};
  return 301 https://$hostname\$request_uri;
}

server {
  listen      [::]:443;
  listen      443;
  server_name ${hostnames[@]};

  ssl on;
  ssl_certificate     $SSL_INUSE/server.crt;
  ssl_certificate_key $SSL_INUSE/server.key;
  ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-RC4-SHA:ECDHE-RSA-AES128-SHA:AES128-GCM-SHA256:RC4:HIGH:!MD5:!aNULL:!EDH:!CAMELLIA;
  ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
  ssl_prefer_server_ciphers on;

  location    / {
    proxy_pass  http://$APP;
EOF

for host in "${hostnames[@]}";
do
  cat <<EOF
    proxy_redirect http://$host:$INT_PORT/ https://$host/;
    proxy_redirect https://$host:$INT_PORT/ https://$host/;
EOF
done

cat <<EOF
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$http_host;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header X-Forwarded-For \$remote_addr;
    proxy_set_header X-Forwarded-Port \$server_port;
    proxy_set_header X-Request-Start \$msec;
  }
}
EOF
