#!/usr/bin/env bash

source "$(dirname $0)/../dokku_common"

function hostnames_for_app() {
	verify_app_name "$1"

	hostname=""
	hostnames=""
	redirect_hostnames=""

	if [[ -f "$DOKKU_ROOT/$APP/REDIRECT_HOSTNAME" ]]; then
		redirect_hostnames=($(<"$DOKKU_ROOT/$APP/REDIRECT_HOSTNAME"))
	fi

	if [[ -f "$DOKKU_ROOT/$APP/HOSTNAME" ]]; then
		hostnames=($(<"$DOKKU_ROOT/$APP/HOSTNAME"))
		if [[ "${hostnames[0]}" != "" ]]; then
			hostname="${hostnames[0]}"
			return
		fi
	fi

	if [[ -f "$DOKKU_ROOT/VHOST" ]]; then
		VHOST=$(< "$DOKKU_ROOT/VHOST")
		SUBDOMAIN="${APP/%\.${VHOST}/}"
		if [[ "$APP" == *.* ]] && [[ "$SUBDOMAIN" == "$APP" ]]; then
			hostname="${APP/\//-}"
		else
			hostname="${APP/\//-}.$VHOST"
		fi

		hostnames="$hostname"
	fi
}
