#!/bin/bash

set -e
pushd $(dirname $0)

export HOME=/root

echo "Starting services..."
sudo service nginx stop || true
sudo service nginx start
sudo service docker start
sudo service ssh start || true
sudo service rsyslog start || true
../start-dokku.sh exit

echo "Removing old containers..."
docker ps -a -q | xargs --no-run-if-empty docker rm -f

echo "Configuring dokku..."
[[ -f ~/.ssh/id_rsa ]] || ssh-keygen -q -t rsa -N "" -f ~/.ssh/id_rsa
cat <<EOF > ~/.ssh/config
Host *
    StrictHostKeyChecking no
EOF
cat ~/.ssh/id_rsa.pub | sudo dokku access:add
ssh dokku@localhost version

TESTS="$@"
[[ $# -eq 0 ]] && TESTS=apps/*

for app_path in $TESTS; do
  app=$(basename $app_path)
  echo "----------------------------------------"
  echo "-----> Running test deploy of $app..."
  echo "----------------------------------------"
  echo ""
  ./test_deploy $app_path localhost
done

echo "=====> DONE!"
