#!/bin/bash

set -e
pushd $(dirname $0)

echo "========================================"
echo "=====> Starting services..."
echo "========================================"
echo ""

sudo service nginx restart
sudo service docker restart
sudo service ssh restart

echo "========================================"
echo "=====> Configuring dokku..."
echo "========================================"
echo ""

[[ -f ~/.ssh/id_rsa ]] || ssh-keygen -q -t rsa -N "" -f ~/.ssh/id_rsa
cat <<EOF > ~/.ssh/config
Host *
    StrictHostKeyChecking no
EOF
sudo sshcommand create dokku /usr/local/bin/dokku
cat ~/.ssh/id_rsa.pub | sudo sshcommand acl-add dokku testkey
sudo dokku plugins-install
ssh dokku@localhost version

echo "========================================"
echo "=====> Running test deploy without VHOST"
echo "========================================"
echo ""

for app_path in apps/*; do
  app=$(basename $app_path)
  echo "----------------------------------------"
  echo "-----> Running test deploy of $app..."
  echo "----------------------------------------"
  echo ""
  ./test_deploy $app_path localhost
done

echo "========================================"
echo "=====> Running test deploy with VHOST"
echo "========================================"
echo ""

sudo bash -c 'echo dokku.me > /home/dokku/VHOST'

for app_path in apps/*; do
  app=$(basename $app_path)
  echo "----------------------------------------"
  echo "-----> Running test deploy of $app..."
  echo "----------------------------------------"
  echo ""
  ./test_deploy $app_path localhost
done

echo "=====> DONE!"
