#!/usr/bin/env bash

if [[ $# -lt 2 ]]; then
    echo "usage: $0 <app> <dokku-host> [forwarded-port]"
    exit 1
fi

set -eo pipefail
SELF=`which $0`;
export APP="$1";
export TARGET="$2";
export FORWARDED_PORT="$3"
export REMOTE="dokku@$TARGET"
export REPO="t-$(basename $APP)-$RANDOM"

TMP=$(mktemp -d -t "$TARGET.XXXXX")
trap "rm -rf $TMP" EXIT
rmdir $TMP && cp -r $(dirname $SELF)/$APP $TMP
cd $TMP
git init -q
git config user.email "robot@example.com"
git config user.name "Test Robot"
git remote add target $REMOTE:$REPO

[[ -f gitignore ]] && mv gitignore .gitignore
git add .

[[ -x pre-commit ]] && ./pre-commit $REMOTE $REPO
git commit -m 'initial commit'
git push target master

cleanup() {
	ssh $REMOTE delete $REPO || true
}

trap cleanup EXIT

export URL=$(ssh $REMOTE url $REPO)$FORWARDED_PORT
export PROXY_URL=$TARGET:80

if [[ ! -x post-deploy ]] || ./post-deploy $REMOTE $REPO $PROXY_URL; then
	for i in 2 4 8
	do
		sleep $i

		if ./check_deploy $URL $PROXY_URL
		then
		    echo "----------------------------------------"
			echo "-----> Deploy SUCCESS ($APP)!" 
		    echo "----------------------------------------"
		    exit 0
		fi
	done
fi

ssh $REMOTE logs $REPO || true

echo "----------------------------------------"
echo "-----> Deploy FAILED ($APP)!" 
echo "----------------------------------------"
exit 1
