#!/usr/bin/env bash

source "$(dirname $0)/../dokku_common"

verify_app_name "$1"

if [[ "$3" != "buildstep" ]]; then
	exit 0;
fi

docker run -d "$IMAGE" /bin/bash -c "rm -rf /app/.ssh" | commit_image "$IMAGE"
