#!/bin/sh
set -e

case "$1" in
  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  configure)
    mandb
    [ ! -x /usr/bin/docker.io ] || ln -sf /usr/bin/docker.io /usr/local/bin/docker
    modprobe aufs || echo "WARNING: Restart server to finish installing dokku!"
    sshcommand create dokku /usr/local/bin/dokku
    usermod -aG docker dokku
    openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
    dokku plugins-install
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
