#!/bin/bash

source "$(dirname $0)/vars"

verify_db_name() {
    sanitize_name "$1" "database name"
    DB_NAME="$1"
}

mysql_shell() {
    DB_USER="$1"
    DB_PASSWORD="$2"
    shift 2
    docker run -i --rm \
            --link="$DB_CONTAINER":"$DB_CONTAINER_LINK" \
            -e MYSQL_PWD="$(cat "$DB_PASSWORD")" \
            "$DB_IMAGE" \
        bash -c "mysql --user=\"$DB_USER\" --host=\"\$MARIADB_PORT_3306_TCP_ADDR\" --port=\"\$MARIADB_PORT_3306_TCP_PORT\" $@"
}

mysql_admin() {
    mysql_shell "root" "$DB_ADMIN_PASSWORD" "$@"
}

case "$1" in
  mariadb:create)
    verify_db_name "$2"
    verify_max_args 2 "$@"
    
    mysql_admin <<EOF
CREATE DATABASE IF NOT EXISTS \`$DB_NAME\` DEFAULT CHARACTER SET \`utf8\` COLLATE \`utf8_unicode_ci\`;
EOF
    info "MariaDB database created: $DB_NAME"
    ;;

  mariadb:delete)
    verify_db_name "$2"
    verify_max_args 2 "$@"

    mysql_admin <<EOF
DROP DATABASE IF EXISTS \`$DB_NAME\`;
EOF
    rm -f $DB_APP_DATABASES*/$DB_NAME
    info "MariaDB database deleted: $DB_NAME"
    ;;

  mariadb:list)
    verify_app_name "$2"
    verify_max_args 2 "$@"

    DB_LINKS="$DB_APP_DATABASES$APP/"
    mkdir -p "$DB_LINKS"
    ls -1 "$DB_LINKS"
    ;;

  mariadb:info)
    verify_app_name "$2"
    verify_db_name "$3"
    verify_max_args 3 "$@"

    DB_PASSWORD="$DB_APP_PASSWORDS$APP"
    DB_LINK="$DB_APP_DATABASES$APP/$DB_NAME"
    [ ! -f "$DB_LINK" ] && fail "$DB_NAME: database is not linked to $APP"
    echo
    DB_USER="$APP"
    DB_PASSWORD="$(cat "$DB_PASSWORD")"
    DB_DATABASE="$DB_NAME"
    docker run -i --rm \
                --link="$DB_CONTAINER":"$DB_CONTAINER_LINK" \
                "$DB_IMAGE" \
                bash - <<EOF
echo "       Host: \$MARIADB_PORT_3306_TCP_ADDR"
echo "       Port: \$MARIADB_PORT_3306_TCP_PORT"
echo "       User: $DB_USER"
echo "       Password: $DB_PASSWORD"
echo "       Database: $DB_DATABASE"
echo
echo "       MARIADB_URL=mysql2://$DB_USER:$DB_PASSWORD@\$MARIADB_PORT_3306_TCP_ADDR:\$MARIADB_PORT_3306_TCP_PORT/$DB_DATABASE"
EOF
    echo
    ;;

  mariadb:link)
    verify_app_name "$2"
    verify_db_name "$3"
    verify_max_args 3 "$@"

    DB_APP_PASSWORD="$DB_APP_PASSWORDS$APP"
    if [ ! -f "$DB_APP_PASSWORD" ]; then
        DB_NEW_PASSWORD="$(generate_random_password)"
        mysql_admin <<EOF
CREATE USER '$APP'@'%' IDENTIFIED BY '$DB_NEW_PASSWORD';
EOF
        echo "$DB_NEW_PASSWORD" > "$DB_APP_PASSWORD"
    fi
    mysql_admin <<EOF
GRANT ALL ON \`$DB_NAME\`.* TO '$APP'@'%';
EOF
    mkdir -p "$DB_APP_DATABASES$APP"
    touch "$DB_APP_DATABASES$APP/$DB_NAME"
    redeploy_app "$APP"
    ;;

  mariadb:unlink)
    verify_app_name "$2"
    verify_db_name "$3"
    verify_max_args 3 "$@"

    mysql_admin <<EOF
REVOKE ALL ON \`$DB_NAME\`.* FROM '$APP'@'%';
EOF
    rm "$DB_APP_DATABASES$APP/$DB_NAME"
    redeploy_app "$APP"
    ;;

  mariadb:console)
    verify_app_name "$2"
    verify_db_name "$3"
    verify_max_args 3 "$@"

    DB_PASSWORD="$DB_APP_PASSWORDS$APP"
    DB_LINK="$DB_APP_DATABASES$APP/$DB_NAME"
    [ ! -f "$DB_LINK" ] && fail "$DB_NAME: database is not linked to $APP"
    shift 2
    docker run -t -i --rm \
            --link="$DB_CONTAINER":"$DB_CONTAINER_LINK" \
            -e DB_DATABASE="$DB_NAME" \
            -e DB_USER="$APP" \
            -e MYSQL_PWD="$(cat "$DB_PASSWORD")" \
            "$DB_IMAGE" \
        bash -c 'mysql -u "$DB_USER" -h "$MARIADB_PORT_3306_TCP_ADDR" -P "$MARIADB_PORT_3306_TCP_PORT" "$DB_DATABASE"'
    ;;

  help)
    cat && cat<<EOF
    mariadb:create <db>         Create a MariaDB database
    mariadb:delete <db>         Delete specified MariaDB database
    mariadb:list <app>          List linked databases
    mariadb:link <app> <db>     Link database to app
    mariadb:unlink <app> <db>   Unlink database from app
    mariadb:info <app> <db>     Display application informations
    mariadb:console <app> <db>  Launch console for MariaDB container
EOF
    ;;

esac
