#!/bin/bash

[[ $1 != mariadb:* ]] && exit 0

APP="$2"
source "$(dirname $0)/vars"

# Create .mariadb directory if does not exist
if [[ ! -d "$DB_APP_ROOT" ]]; then
    mkdir -p "$DB_APP_ROOT"
    chown -R dokku: "$DB_APP_ROOT"
fi

case "$1" in
  mariadb:create)
    require_image "$DB_IMAGE"
    [ -f "$DB_HOST_PASSWORD" ] || generate_random_password > "$DB_HOST_PASSWORD" || true
    docker stop "$DB_CONTAINER" 1>/dev/null 2>/dev/null || true
    docker rm "$DB_CONTAINER" 1>/dev/null 2>/dev/null || true
    docker run --detach --publish=3306 \
                --volume="$DB_HOST_VOLUME":"$DB_CONTAINER_VOLUME" \
                --volume="$DB_HOST_PASSWORD":"$DB_CONTAINER_PASSWORD" \
                --name="$DB_CONTAINER" \
                "$DB_IMAGE" \
                /usr/bin/start_mariadb.sh >/dev/null
    sleep 1s
    info "MariaDB container created: $DB_CONTAINER"
    dokku mariadb:info $APP
    redeploy_app "$APP"
    ;;

  mariadb:delete)
    docker rm -v -f "$DB_CONTAINER" 1>/dev/null 2>/dev/null
    rm -f "$DB_APP_ID"
    info "MariaDB container deleted: $DB_CONTAINER"
    redeploy_app "$APP"
    ;;

  mariadb:info)
    [ ! -f "$DB_HOST_PASSWORD" ] && fail "Unknown (or too old) MariaDB container"
    require_image "$DB_IMAGE"
    echo
    docker run -i --rm \
                --link="$DB_CONTAINER":"$DB_CONTAINER_LINK" \
                --volume="$DB_HOST_PASSWORD":"$DB_CONTAINER_PASSWORD" \
                "$DB_IMAGE" \
                bash - <<EOF
echo "       Host: \$MARIADB_PORT_3306_TCP_ADDR"
echo "       Port: \$MARIADB_PORT_3306_TCP_PORT"
echo "       User: root"
echo "       Password: \$(cat "$DB_CONTAINER_PASSWORD")"
echo "       Database: db"
echo
echo "       MARIADBL_URL=mysql2://root:\$(cat "$DB_CONTAINER_PASSWORD")@\$MARIADB_PORT_3306_TCP_ADDR:\$MARIADB_PORT_3306_TCP_PORT/db"
EOF
    echo
    ;;

  mariadb:logs)
    docker logs "$DB_CONTAINER" | tail -n 1000
    ;;

  mariadb:console)
    shift 2
    docker run -t -i --rm \
            --link="$DB_CONTAINER":"$DB_CONTAINER_LINK" \
            --volume="$DB_HOST_PASSWORD":"$DB_CONTAINER_PASSWORD" \
            "$DB_IMAGE" \
        bash -c 'mysql -u root -h "$MARIADB_PORT_3306_TCP_ADDR" -P "$MARIADB_PORT_3306_TCP_PORT" --password="$(cat "$DB_CONTAINER_PASSWORD")" db'
    ;;

  help)
    cat && cat<<EOF
    mariadb:create <app>     Create a MariaDB container
    mariadb:delete <app>     Delete specified MariaDB container
    mariadb:info <app>       Display database informations
    mariadb:logs <app>       Display last logs from MariaDB container
    mariadb:console <app>    Launch console for MariaDB container
EOF
    ;;

esac
