#!/bin/bash

[[ $1 != mariadb:* ]] && exit 0

APP="$2"
source "$(dirname $0)/common.bash"

# Create .mariadb directory if does not exist
if [[ ! -d "$DB_APP_ROOT" ]]; then
    mkdir -p "$DB_APP_ROOT"
    chown -R dokku: "$DB_APP_ROOT"
fi

case "$1" in
  mariadb:create)
    require_image "$DB_IMAGE"
    [ ! -f "$DB_PASSWORD_FILE" ] && generate_random_password > $DB_PASSWORD_FILE
    docker stop "$DB_CONTAINER" 1>&2 2>/dev/null || true
    docker rm "$DB_CONTAINER" 1>&2 2>/dev/null || true
    docker run --detach --publish=3306 \
                --volume="$DB_ROOT":"$DB_CONTAINER_VOLUME" \
                --volume="$DB_PASSWORD_FILE":"$DB_CONTAINER_PASSWORD" \
                --name="$DB_CONTAINER" \
                "$DB_IMAGE" \
                /usr/bin/start_mariadb.sh >/dev/null
    sleep 1s
    echo
    info "MariaDB container created: $DB_CONTAINER"
    deploy_app "$APP"
    sleep 1
    dokku mariadb:info $APP
    ;;

  mariadb:delete)
    docker rm -f "$DB_CONTAINER" 1>&2 2>/dev/null
    rm -rf "$DB_PASSWORD_FILE"
    rm -rf "$DB_VOLUME"
    echo
    info "MariaDB container deleted: $DB_CONTAINER"
    ;;

  mariadb:info)
    [ ! -f "$DB_PASSWORD_FILE" ] && fail "Unknown (or too old) MariaDB container"
    require_image "$DB_IMAGE"
    echo
    docker run -i --rm --link="$DB_CONTAINER":"$DB_CONTAINER_LINK" --volume="$DB_PASSWORD_FILE":"$DB_CONTAINER_PASSWORD" "$DB_IMAGE" bash - <<EOF
echo "       Host: \$MARIADB_PORT_3306_TCP_ADDR"
echo "       Port: \$MARIADB_PORT_3306_TCP_PORT"
echo "       User: root"
echo "       Password: \$(cat "$DB_CONTAINER_PASSWORD")"
echo "       Database: db"
EOF
    echo
    ;;

  mariadb:logs)
    docker logs "$DB_CONTAINER" | tail -n 1000
    ;;

  help)
    cat && cat<<EOF
    mariadb:create <app>     Create a MariaDB container
    mariadb:delete <app>     Delete specified MariaDB container
    mariadb:info <app>       Display database informations
    mariadb:logs <app>       Display last logs from MariaDB container
EOF
    ;;

esac
