#!/bin/bash

source "$(dirname $0)/../dokku_common"
source "$(dirname $0)/../dokku_common_database"

DB_ROOT="$DOKKU_ROOT/.mariadb"
DB_IMAGE="${MARIADB_IMAGE:-ayufan/dokku-alt-mariadb}"
DB_VOLUME="$DB_ROOT/mysql"
DB_ADMIN_PASSWORD="$DB_ROOT/mysql_password"
DB_CONTAINER="mariadb_single_container"
DB_CONTAINER_LINK="mariadb"
DB_CONTAINER_VOLUME="${MARIADB_CONTAINER_VOLUME:-/opt/mysql}"
DB_CONTAINER_PASSWORD="${MARIADB_CONTAINER_PASSWORD:-/opt/mysql_password}"
DB_HOST="$DB_CONTAINER_LINK"
DB_PORT="${MARIADB_PORT:-3306}"
DB_PROTOCOL="${MARIADB_PROTOCOL:-mariadb}"
DB_COMMAND="${MARIADB_COMMAND:-/usr/bin/start_mariadb.sh}"

DB_APP_PASSWORDS="$DB_ROOT/pwd_app_"
DB_APP_DATABASES="$DB_ROOT/dbs_app_"
