#!/bin/bash

source "$(dirname $0)/../dokku_common"

verify_app_name "$1"

cat

if config_get DOKKU_CHECKS_WAIT >/dev/null || 
    config_get DOKKU_CHECKS_TIMEOUT >/dev/null || 
    config_get DOKKU_CHECKS_RETRY >/dev/null
then
    echo "CHECKS"
fi
