#!/usr/bin/env bash

source "$(dirname $0)/../dokku_common"

case "$1" in
  rebuild)
    verify_app_name "$2"
    verify_max_args 3 "$@"

    print_acl_access "developer" "$2"
    ;;

  rebuild:force)
    verify_app_name "$2"
    verify_max_args 3 "$@"

    print_acl_access "developer" "$2"
    ;;
esac
