#!/bin/bash

# Build docker image
git clone https://github.com/jlachowski/dokku-rabbitmq-dockerfiles.git /tmp/dokku-rabbitmq-dockerfiles
docker build -t jlachowski/rabbitmq /tmp/dokku-rabbitmq-dockerfiles
rm -rf /tmp/dokku-rabbitmq-dockerfiles
