#!/bin/bash

source "$(dirname $0)/vars"

# Build docker image
docker pull "$DB_IMAGE"

# Create .mariadb directory if does not exist
if [[ ! -d "$DB_ROOT" ]]; then
    mkdir -p "$DB_ROOT"
    chown -R dokku: "$DB_ROOT"
fi

# Create root password if not specified
if [[ ! -f "$DB_ADMIN_PASSWORD" ]]; then
	generate_random_password > "$DB_ADMIN_PASSWORD"
fi

restart_database_container

cat
