#!/bin/bash

source "$(dirname $0)/vars"

# Build docker image
docker build -t "$DB_IMAGE" "$CWD/dockerfiles"

# Create .mariadb directory if does not exist
if [[ ! -d "$DB_ROOT" ]]; then
    mkdir -p "$DB_ROOT"
    chown -R dokku: "$DB_ROOT"
fi

# Create root password if not specified
if [[ ! -f "$DB_ADMIN_PASSWORD" ]]; then
	generate_random_password > "$DB_ADMIN_PASSWORD"
fi

stop_and_remove_container "$DB_CONTAINER"
ensure_database_container_is_running

cat
