#!/bin/bash

source "$(dirname $0)/vars"

verify_app_name "$1"

DB_LINKS="$DB_APP_DATABASES$APP/"
DB_APP_PASSWORD="$DB_APP_PASSWORDS$APP"

# inject MARIADB_URL
if [[ -d "$DB_LINKS" ]] && [[ -f "$DB_APP_PASSWORD" ]] && [[ $(ls -1 "$DB_LINKS" | wc -l) -gt 0 ]]; then
	ls -1 "$DB_LINKS" | while read DB_NAME; do
		docker run -i -a stdin "$IMAGE" /bin/bash -c "cat > /app/.profile.d/pgsql_env" <<EOF | commit_image "$IMAGE"
[ "\$POSTGRESQL_NAME" != "" ] && export DATABASE_URL=mysql2://$APP:$(cat "$DB_APP_PASSWORD")@\$POSTGRESQL_PORT_${DB_PORT}_TCP_ADDR:\$POSTGRESQL_PORT_${DB_PORT}_TCP_PORT/$DB_NAME
EOF
		verbose "Linking PostgreSQL database $DB_NAME to application" 1>&2
	done
fi
