#!/usr/bin/env bash

source "$(dirname $0)/vars"

verify_app_name "$1"

DB_LINKS="$DB_APP_DATABASES$APP/"
DB_APP_PASSWORD="$DB_APP_PASSWORDS$APP"
rm -rf "$DB_LINKS" "$DB_APP_PASSWORD"

# TODO: drop user
