#!/bin/bash

source "$(dirname $0)/vars"

verify_app_name "$1"

DB_LINKS="$DB_APP_DATABASES$APP/"
DB_APP_PASSWORD="$DB_APP_PASSWORDS$APP"

# inject MARIADB_URL
if [[ -d "$DB_LINKS" ]] && [[ -f "$DB_APP_PASSWORD" ]] && [[ $(ls -1 "$DB_LINKS" | wc -l) -gt 0 ]]; then
	ls -1 "$DB_LINKS" | while read DB_NAME; do
		ensure_database_container_is_running
		break
	done
fi
