#!/bin/bash

source "$(dirname $0)/../dokku_common"

DB_ROOT="$DOKKU_ROOT/.pgsql"
DB_IMAGE="kloadut/postgresql"
DB_VOLUME="$DB_ROOT/postgresql"
DB_ADMIN_PASSWORD="$DB_ROOT/postgresql_password"
DB_CONTAINER="postgresql_single_container"
DB_CONTAINER_LINK="postgresql"
DB_CONTAINER_VOLUME="/opt/postgresql"
DB_CONTAINER_PASSWORD="/opt/postgresql_password"
DB_PORT=5432

DB_APP_PASSWORDS="$DB_ROOT/pwd_app_"
DB_APP_DATABASES="$DB_ROOT/dbs_app_"

function ensure_database_container_is_running() {
	# remove it silently
	remove_container "$DB_CONTAINER"

	# and start detached
	docker run --detach "--publish=$DB_PORT" \
	           --volume="$DB_VOLUME":"$DB_CONTAINER_VOLUME" \
	           --volume="$DB_ADMIN_PASSWORD":"$DB_CONTAINER_PASSWORD" \
	           --name="$DB_CONTAINER" \
	           "$DB_IMAGE" \
	           /usr/bin/start_pgsql.sh >/dev/null
}
