#!/bin/bash

source "$(dirname $0)/../dokku_common"

DB_ROOT="$DOKKU_ROOT/.pgsql"
DB_IMAGE="kloadut/postgresql"
DB_VOLUME="$DB_ROOT/postgresql"
DB_ADMIN_PASSWORD="$DB_ROOT/postgresql_password"
DB_CONTAINER="postgresql_single_container"
DB_CONTAINER_LINK="postgresql"
DB_CONTAINER_VOLUME="/opt/postgresql"
DB_CONTAINER_PASSWORD="/opt/postgresql_password"
DB_PORT=5432

DB_APP_PASSWORDS="$DB_ROOT/pwd_app_"
DB_APP_DATABASES="$DB_ROOT/dbs_app_"

function start_database_container() {
	docker run --detach "--publish=$DB_PORT" \
	           --volume="$DB_VOLUME":"$DB_CONTAINER_VOLUME" \
	           --volume="$DB_ADMIN_PASSWORD":"$DB_CONTAINER_PASSWORD" \
	           --name="$DB_CONTAINER" \
	           "$DB_IMAGE" \
	           /usr/bin/start_pgsql.sh >/dev/null
}

function restart_database_container() {
	stop_and_remove_container "$DB_CONTAINER"
	start_database_container
}

function ensure_database_container_is_running() {
	remove_container "$DB_CONTAINER"
	start_database_container 2>/dev/null || true
}

function db_info() {
    APP="$1"
    DB_NAME="$2"
    DB_PASSWORD="$DB_APP_PASSWORDS$APP"
    DB_LINK="$DB_APP_DATABASES$APP/$DB_NAME"
    DB_PASSWORD="$(cat "$DB_PASSWORD" 2>/dev/null)"
    DB_USER="$APP"
    DB_DATABASE="$DB_NAME"
    DB_URL="postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_DATABASE"
    [[ ! -f "$DB_LINK" ]] && return 1
    return 0
}
