#!/usr/bin/env bash

source "$(dirname $0)/../dokku_common"

cat

case "$1" in
  git-hook)
    verify_app_name "$2"
    print_acl_access "deploy" "$APP"
    ;;

  git-*)
    APP="$(echo "$2" | perl -pe 's/(?<!\\)'\''//g' | sed 's/\\'\''/'\''/g')"
    check_app_name "$APP"
    print_acl_access "deploy" "$APP"
    ;;
esac
