#!/usr/bin/env bash

source "$(dirname $0)/../dokku_common"

case "$1" in
  delete)
    verify_app_name "$2"

    if [[ ! -d "$DOKKU_ROOT/$APP" ]]; then
        echo "App does not exist"
        exit 1
    fi

    pluginhook pre-delete $APP

    stop_and_remove_container "$APP_ALL_NAMES"
    remove_image "$IMAGE"

    pluginhook post-delete $APP
    ;;

  logs)
    verify_app_name "$2"

    if [[ $3 == "-t" ]]; then
      docker logs --follow "$APP_NAME"
    else
      docker logs "$APP_NAME" | tail -n 100
    fi
    ;;

  logs:worker)
    verify_app_name "$2"

    if [[ $3 == "-t" ]]; then
      docker logs --follow "$APP_WORKER_NAME"
    else
      docker logs "$APP_WORKER_NAME" | tail -n 100
    fi
    ;;

  run)
    verify_app_name "$2"

    if [[ ! -d "$DOKKU_ROOT/$APP" ]]; then
        echo "App $APP does not exist"
        exit 1
    fi
    shift 2

    docker rm -f "$APP_RUN_NAME" 1>/dev/null 2>/dev/null || true

    DOCKER_ARGS=$(: | pluginhook docker-args $APP)
    docker run --rm --name="$APP_RUN_NAME" -i -t $DOCKER_ARGS "$IMAGE" /exec "$@"
    ;;

  url)
    verify_app_name "$2"

    if [[ ! -d "$DOKKU_ROOT/$APP" ]]; then
        echo "App $APP does not exist"
        exit 1
    fi

    if [[ -f "$DOKKU_ROOT/$APP/URL" ]]; then
      echo $(< "$DOKKU_ROOT/$APP/URL")
    fi
    ;;

  version)
    cat "$(dirname $0)/../../VERSION" || {
      echo "Unable to determine dokku's version" 2>&1
      exit 1
    }
    ;;

  help)
    cat && cat<<EOF
    delete <app>                                    Delete an application
    logs <app> [-t]                                 Show the last logs for an application (-t follows)
    run <app> <cmd>                                 Run a command in the environment of an application
    url <app>                                       Show the URL for an application
    version                                         Print dokku's version
EOF
    ;;

esac

