#!/usr/bin/env bash

source "$(dirname $0)/../dokku_common"

cat

case "$1" in
  logs)
    verify_app_name "$2"
    print_acl_access "developer" "$2"

    if [[ $3 == "-t" ]] || [[ $3 == "-f" ]]; then
      docker logs --follow "$APP_NAME"
    else
      docker logs "$APP_NAME" | tail -n 100
    fi
    ;;

  run)
    verify_app_name "$2"
    print_acl_access "developer" "$2"
    ;;

  enter)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_acl_access "developer" "$2"
    ;;

  exec)
    verify_app_name "$2"
    print_acl_access "developer" "$2"
    ;;

  url)
    verify_app_name "$2"
    print_acl_access "developer" "$2"
    ;;
esac
