#!/usr/bin/env bash

source "$(dirname $0)/../dokku_common"

verify_app_name "$1"
rm -rf "$APP_DIR"

# untag and potentially remove all application containers
docker rmi \
	"$IMAGE_GENERIC:build" \
	"$IMAGE_GENERIC:release" \
	"$IMAGE_GENERIC:deployed" \
	"$IMAGE_GENERIC:latest" \
	1>/dev/null 2>/dev/null || true
