#!/usr/bin/env bash

source "$(dirname $0)/../dokku_common"

verify_app_name "$1"
docker run --rm --entrypoint="/bin/bash" -v "$CACHE_DIR":/cache "$IMAGE" -c find /cache -depth -mindepth 1 -maxdepth 1 -exec rm -Rf {} \;
