#!/usr/bin/env bash

source "$(dirname $0)/vars"

case "$1" in
  storage:list)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    storage_for_app "$APP"
    cat "$STORAGE_PATHS"
	;;

  storage:add)
    verify_app_name "$2"
    verify_max_args 3 "$@"
    storage_for_app "$APP"

    realpath="$(readlink -m "$3")"
    [[ "$3" == "$realpath" ]] || fail "$3: invalid path ($realpath)"

    info "Adding path '$realpath' to '$APP' application"
    info "Current paths for '$APP' application"

    cat "$STORAGE_PATHS" | (
      cat;
      echo "$realpath"
    ) | sort -u | tee "$STORAGE_PATHS.tmp" && mv "$STORAGE_PATHS.tmp" "$STORAGE_PATHS"

    deploy_app "$APP"
	;;

  storage:remove)
    verify_app_name "$2"
    verify_max_args 3 "$@"
    storage_for_app "$APP"

    realpath="$(readlink -m "$3")"
    [[ "$3" == "$realpath" ]] || fail "$3: invalid path ($realpath)"

    info "Removing path '$realpath' from '$APP' application"
    info "Current paths for '$APP' application"
    comm -23 "$STORAGE_PATHS" <(echo "$realpath") | tee "$STORAGE_PATHS.tmp" && mv "$STORAGE_PATHS.tmp" "$STORAGE_PATHS" 

    deploy_app "$APP"
	;;

  help)
    cat && cat<<EOF
    storage:list <app>           List persistent paths
    storage:add <app> <path>     Add persistent path
    storage:remove <app> <path>  Remove persistent path
EOF
    ;;
esac
