#!/bin/bash

source "$(dirname $0)/vars"

verify_app_name "$1"

cat

PREBOOT_WAIT_TIME="$(config_get PREBOOT_WAIT_TIME || true)"
PREBOOT_WAIT_TIME="${PREBOOT_WAIT_TIME:-5}"

if [[ "$PREBOOT_WAIT_TIME" != "" ]]; then
    verbose "Waiting $PREBOOT_WAIT_TIME seconds for boot..."
    sleep "$PREBOOT_WAIT_TIME"
fi
