#!/usr/bin/env bash

source "$(dirname $0)/vars"

cat

case "$1" in
  preboot:status)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_acl_access "developer" "$2"
    ;;

  preboot:enable)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_acl_access "developer" "$2"
    ;;

  preboot:disable)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_acl_access "developer" "$2"
    ;;

  preboot:wait:time)
    verify_app_name "$2"
    verify_max_args 3 "$@"
    print_acl_access "developer" "$2"
    ;;

  preboot:cooldown:time)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_acl_access "developer" "$2"
    ;;
esac
