#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

# Check if name is specified
if [[ $1 == apps:* ]]; then
    if [[ -z $2 ]]; then
        echo "You must specify an app name"
        exit 1
    else
        APP="$2"
        # Check if app exists with the same name
        if [[ -d "$DOKKU_ROOT/$APP" ]]; then
            APP_EXISTS=true
        else
            APP_EXISTS=false
        fi
    fi
fi

case "$1" in
  apps)
    ls -1 -d $DOKKU_ROOT/*/ | xargs -L1 basename
    ;;

  apps:status)
	ID=$(< "$DOKKU_ROOT/$APP/CONTAINER")
	if docker ps --no-trunc -q | grep -q $ID
	then
		echo "$APP is running."
	else
		echo "$APP is stopped."
	fi
	;;

  apps:start)
	ID=$(< "$DOKKU_ROOT/$APP/CONTAINER")
    docker start $ID
	;;

  apps:stop)
	ID=$(< "$DOKKU_ROOT/$APP/CONTAINER")
    docker stop $ID
	;;

  help)
    cat && cat<<EOF
    apps                  List apps
    apps:status <app>     Status of specific apps
    apps:start <app>	  Stop specific apps
    apps:stop <app>		  Stop specific apps
EOF
    ;;
esac
