#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

# Check if name is specified
if [[ $1 == start-args ]] || [[ $1 == start-args:* ]]; then
  if [[ -z $2 ]]; then
    echo "You must specify an app name"
    exit 1
  else
    APP="$2"
    START_ARGS_FILE="$DOKKU_ROOT/$APP/START_ARGS"
    START_ARGS_FILE_TEMP="$DOKKU_ROOT/$APP/START_ARGS.tmp"

    # Check if app exists with the same name
    if [ ! -d "$DOKKU_ROOT/$APP" ]; then
      echo "App $APP does not exist"
      exit 1
    fi

    [ -f $START_ARGS_FILE ] || {
      # echo "-----> Creating $START_ARGS_FILE"
      touch $START_ARGS_FILE
    }
  fi
fi

case "$1" in
  start-args)
    : | pluginhook start-args "$APP"
  ;;

  start-args:set)
    APP="$2"; APP_DIR="$DOKKU_ROOT/$APP"

    shift 2

    echo "$@" > "$START_ARGS_FILE_TEMP"
    if ! cmp -s "$START_ARGS_FILE" "$START_ARGS_FILE_TEMP"; then
      echo "-----> Setting start args and restarting $APP"
      cp -f "$START_ARGS_FILE_TEMP" "$START_ARGS_FILE"
      dokku rebuild "$APP"
    fi
    rm -f "$START_ARGS_FILE_TEMP"
  ;;

  help|start-args:help)
    cat && cat<<EOF
    start-args <app>                                Display the start args for an app
    start-args:set <app> arg1 [arg2 ...]            Set the start args for an app
EOF
  ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
