#!/bin/bash

source "$(dirname $0)/../dokku_common"
source "$(dirname $0)/../dokku_common_database"

DB_ROOT="$DOKKU_ROOT/.mongodb"
DB_IMAGE="${MONGODB_IMAGE:-ayufan/dokku-alt-mongodb}"
DB_VOLUME="$DB_ROOT/mongodb"
DB_ADMIN_PASSWORD="$DB_ROOT/mongodb_password"
DB_CONTAINER="mongodb_single_container"
DB_CONTAINER_LINK="mongodb"
DB_CONTAINER_VOLUME="${MONGODB_CONTAINER_VOLUME:-/opt/mongodb}"
DB_CONTAINER_PASSWORD="${MONGODB_CONTAINER_PASSWORD:-/opt/mongodb_password}"
DB_HOST="$DB_CONTAINER_LINK"
DB_PORT="${MONGODB_PORT:-27017}"
DB_PROTOCOL="${MONGODB_PROTOCOL:-mongodb}"
DB_COMMAND="${MONGODB_COMMAND:-/usr/bin/start_mongodb.sh}"

DB_APP_PASSWORDS="$DB_ROOT/pwd_app_"
DB_APP_DATABASES="$DB_ROOT/dbs_app_"
