#!/bin/bash

source "$(dirname $0)/../dokku_common"

DB_ROOT="$DOKKU_ROOT/.mongodb"
DB_IMAGE="ayufan/mongodb"
DB_VOLUME="$DB_ROOT/mongodb"
DB_ADMIN_PASSWORD="$DB_ROOT/mongodb_password"
DB_CONTAINER="mongodb_single_container"
DB_CONTAINER_LINK="mongodb"
DB_CONTAINER_VOLUME="/opt/mongodb"
DB_CONTAINER_PASSWORD="/opt/mongodb_password"
DB_PORT=27017

DB_APP_PASSWORDS="$DB_ROOT/pwd_app_"
DB_APP_DATABASES="$DB_ROOT/dbs_app_"
