#!/bin/bash

source "$(dirname $0)/../dokku_common"

DB_ROOT="$DOKKU_ROOT/.mongodb"
DB_IMAGE="ayufan/mongodb"
DB_VOLUME="$DB_ROOT/mongodb"
DB_ADMIN_PASSWORD="$DB_ROOT/mongodb_password"
DB_CONTAINER="mongodb_single_container"
DB_CONTAINER_LINK="mongodb"
DB_CONTAINER_VOLUME="/opt/mongodb"
DB_CONTAINER_PASSWORD="/opt/mongodb_password"
DB_PORT=27017

DB_APP_PASSWORDS="$DB_ROOT/pwd_app_"
DB_APP_DATABASES="$DB_ROOT/dbs_app_"

function ensure_database_container_is_running() {
	# remove it silently
	remove_container "$DB_CONTAINER"

	# and start detached
	docker run --detach "--publish=$DB_PORT" \
	           --volume="$DB_VOLUME":"$DB_CONTAINER_VOLUME" \
	           --volume="$DB_ADMIN_PASSWORD":"$DB_CONTAINER_PASSWORD" \
	           --name="$DB_CONTAINER" \
	           "$DB_IMAGE" \
	           /usr/bin/start_mongodb.sh >/dev/null
}
