#!/usr/bin/env bash

source "$(dirname $0)/../dokku_common"

cat

case "$1" in
  apps:status|status)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_app_acl_access "developer"
	;;

  apps:start|start)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_app_acl_access "developer"
	;;

  apps:stop|stop)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_app_acl_access "developer"
	;;

  apps:disable|disable)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_app_acl_access "developer"
  ;;

  apps:enable|enable)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_app_acl_access "developer"
  ;;

  apps:restart|restart)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_app_acl_access "developer"
    ;;

  apps:top|top)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_app_acl_access "developer"
    ;;
esac
