#!/usr/bin/env bash

source "$(dirname $0)/../dokku_common"

verify_app_name "$1"

cat

case "$2" in
	build)
		if DOKKU_USER_ID=$(config_get DOKKU_USER_ID); then
			echo "-e DOKKU_USER_ID=$(printf "%q" $DOKKU_USER_ID)"
		fi

		if DOKKU_RANDOM_USER_ID=$(config_get DOKKU_RANDOM_USER_ID); then
			echo "-e DOKKU_RANDOM_USER_ID=$(printf "%q" $DOKKU_RANDOM_USER_ID)"
		fi
		;;

	*)
		;;
esac
