#!/usr/bin/env bash

source "$(dirname $0)/../dokku_common"

verify_app_name "$1"

SOURCE_ENV_PATH="$APP_DIR/ENV"

if [[ -f "$SOURCE_ENV_PATH" ]]; then
  info "Installing ENV in build environment ..." 1>&2
  cat "$SOURCE_ENV_PATH" | docker run --entrypoint="/bin/bash" -i -a stdin "$IMAGE" -c "mkdir -p /app && cat >> /app/.env" | commit_image "$IMAGE"
fi
