#!/bin/bash

source "$(dirname $0)/vars"

case "$1" in
  htpasswd:add)
    verify_app_name "$2"
    verify_max_args 3 "$@"
    print_acl_access "developer" "$2"
    ;;

  htpasswd:remove)
    verify_app_name "$2"
    verify_max_args 3 "$@"
    print_acl_access "developer" "$2"
    ;;

  htpasswd:disable)
    verify_app_name "$2"
    verify_max_args 2 "$@"
    print_acl_access "developer" "$2"
    ;;
esac
