#!/bin/bash

source "$(dirname $0)/vars"

case "$1" in
  redis:create)
    redis_for_app "$2"
    verify_max_args 2 "$@"

    mkdir -p "$DB_VOLUME"
    info "Redis database created: $DB_CONTAINER"
    dokku config:set "$APP" "REDIS_URL=$DB_URL"
    ;;

  redis:delete)
    redis_for_app "$2"
    verify_max_args 2 "$@"

    stop_and_remove_container "$DB_CONTAINER"
    rm -rf "$DB_VOLUME"
    info "Redis database deleted: $DB_CONTAINER"
    dokku config:unset "$APP" REDIS_URL
    ;;

  redis:info)
    redis_for_app "$2"
    verify_max_args 2 "$@"

    [[ ! -d "$DB_VOLUME" ]] && fail "$DB_CONTAINER: database is not linked to $APP"

    echo
    cat <<EOF
echo "       Host: $DB_HOST"
echo "       Port: $DB_PORT"
echo
echo "       REDIS_URL=$DB_URL"
EOF
    echo
    ;;

  help)
    cat && cat<<EOF
    redis:create <app>          Create a Redis database
    redis:delete <app>          Delete specified Redis database
    redis:info <app>            Display application information
EOF
    ;;

esac
