#!/bin/bash

source "$(dirname $0)/vars"

# Build docker image
docker build -t "$DB_IMAGE" "$CWD/dockerfiles"

# Create .redis directory if does not exist
if [[ ! -d "$DB_ROOT" ]]; then
    mkdir -p "$DB_ROOT"
    chown -R dokku: "$DB_ROOT"
fi

cat
