#!/bin/bash

source "$(dirname $0)/../dokku_common"

DB_ROOT="$DOKKU_ROOT/.redis"
DB_IMAGE="luxifer/redis"
DB_CONTAINER_LINK="redis"
DB_CONTAINER_VOLUME="/var/lib/redis"
DB_PORT=6379

function redis_for_app() {
	verify_app_name "$1"
	DB_VOLUME="$DB_ROOT/$APP"
	DB_CONTAINER="redis_$APP"
}

function start_database_container() {
	docker run --detach "--publish=$DB_PORT" \
	           --volume="$DB_VOLUME":"$DB_CONTAINER_VOLUME" \
	           --name="$DB_CONTAINER" \
	           "$DB_IMAGE" \
	           /usr/bin/start_redis.sh >/dev/null
}

function restart_database_container() {
	stop_and_remove_container "$DB_CONTAINER"
	start_database_container
}

function ensure_database_container_is_running() {
	remove_container "$DB_CONTAINER"
	start_database_container 2>/dev/null || true
}
