#!/bin/bash

source "$(dirname $0)/../dokku_common"

DB_ROOT="$DOKKU_ROOT/.redis"
DB_IMAGE="luxifer/redis"
DB_CONTAINER_LINK="redis"
DB_CONTAINER_VOLUME="/var/lib/redis"
DB_PORT=6379

function redis_for_app() {
	verify_app_name "$1"
	DB_VOLUME="$DB_ROOT/$APP"
	DB_CONTAINER="redis_$APP"
}
