#!/bin/bash
case "$1" in
  pre-build)
    cat
    echo "bar pre-build $2 $3 $4 $5"
    ;;

  pre-deploy)
    echo "bar pre-deploy"
    ;;
  
  text)
    cat | ruby -e "puts STDIN.read.strip.reverse"
    ;;
  
  *)
    exit 1
    ;;
esac