#!/bin/bash
case "$1" in
  pre-build)
    cat
    echo "foo pre-build $@"
    ;;

  post-build)
    echo "foo post-build"
    ;;  
    
  text)
    cat | python -c "import sys;sys.stdout.write(sys.stdin.read().upper())"
    ;;
    
  *)
    exit 1
    ;;
esac